<h3>Nova Categoria</h3>

<br />

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('livraria-admin',array('controller'=>'categoria','action'=>'new'))); 

$form->prepare();
echo $this->form()->OpenTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome')). "<br><br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();


